source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TextSwitch_Example', :exclusive => true do
  pod "TextSwitch", :path => "../"
  pod "ECExtension"
end

target 'TextSwitch_Tests', :exclusive => true do
  pod "TextSwitch", :path => "../"

  
end
